services:
  - type: web
    name: neurocloud
    env: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
